title: Blandine JATSA NGUETSE
logo: /assets/img/profilsinkedIn.PNG
description: >
 2 ans d’expériences professionnelles
 <br>
 Poste en CDI, disponibilité : Immédiate
 blandinenguetse@gmail.com
 <br>
 +33 7 51 29 08 53
 <br> 
 <a href="https://www.linkedin.com/in/blandine-jatsa-nguetse-ingenieur-data-scientist-connaissance-client-cdi/"> Mon Profile LinkedIn </a> 

# show_download: true
theme: jekyll-theme-minimal
