title: Blandine JATSA NGUETSE
logo: /assets/img/profilsinkedIn.PNG
description: >
 2 ans d'XP
 <br>
 blandinenguetse@gmail.com
 <br>
 +33 7 51 29 08 53

# show_download: true
theme: jekyll-theme-minimal
